
name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - Copilot code review
      - Copilot coding agent
      - Test
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: http://135.232.224.86:8080
    permissions:
      actions: read
